//! The cross-language golden vectors (fixtures/vectors/, generated by the
//! Python reference): this crate must reproduce Python's canonical bytes,
//! verify Python-signed envelopes, and agree on every graph delta verdict.

use std::path::PathBuf;

use secdogie_graph::canon::{self, Value};
use secdogie_graph::dag::{Config, DagStore, Outcome};
use secdogie_graph::delta::{self, state_key};
use secdogie_graph::did::did_from_pubkey;
use secdogie_graph::envelope;

fn load(name: &str) -> Value {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../fixtures/vectors")
        .join(name);
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    canon::parse_with(
        &text,
        canon::Limits {
            max_bytes: 8 << 20,
            max_depth: 64,
        },
    )
    .expect("vector file parses")
}

fn get<'a>(v: &'a Value, k: &str) -> &'a Value {
    v.as_obj()
        .and_then(|m| m.get(k))
        .unwrap_or_else(|| panic!("missing {k}"))
}

fn s<'a>(v: &'a Value, k: &str) -> &'a str {
    get(v, k)
        .as_str()
        .unwrap_or_else(|| panic!("{k} is not a string"))
}

fn did_from_seed_hex(hex: &str) -> String {
    let seed: Vec<u8> = (0..32)
        .map(|i| u8::from_str_radix(&hex[2 * i..2 * i + 2], 16).unwrap())
        .collect();
    let sk = ed25519_dalek::SigningKey::from_bytes(&seed.try_into().unwrap());
    did_from_pubkey(&sk.verifying_key().to_bytes())
}

#[test]
fn canonical_bytes_match_python() {
    let v = load("canonical.json");
    for case in get(&v, "cases").as_arr().unwrap() {
        let parsed =
            canon::parse(s(case, "input")).unwrap_or_else(|e| panic!("{}: {e}", s(case, "name")));
        let out = canon::to_string(&parsed);
        assert_eq!(out, s(case, "canonical"), "{}", s(case, "name"));
        assert_eq!(
            delta::sha256_hex(out.as_bytes()),
            s(case, "sha256"),
            "{}",
            s(case, "name")
        );
    }
}

#[test]
fn refuses_every_reject_case() {
    let v = load("canonical.json");
    for case in get(&v, "reject").as_arr().unwrap() {
        let err = canon::parse(s(case, "input")).expect_err(s(case, "name"));
        let want = s(case, "reason");
        let ok =
            err.reason == want || (want == "invalid JSON" && err.reason.starts_with("invalid"));
        assert!(
            ok,
            "{}: got {:?}, want {want:?}",
            s(case, "name"),
            err.reason
        );
    }
}

#[test]
fn verifies_python_signed_authorization_and_dialogue_envelopes() {
    let g = load("gate2.json");
    let operator = get(&g, "operator");
    let node = get(&g, "node");
    assert_eq!(
        did_from_seed_hex(s(operator, "seed_hex")),
        s(operator, "did")
    );
    assert_eq!(did_from_seed_hex(s(node, "seed_hex")), s(node, "did"));

    let token = canon::parse(s(get(&g, "token"), "wire")).unwrap();
    let verified = envelope::verify(token.as_obj().unwrap()).expect("token signature verifies");
    assert_eq!(verified.signer, s(operator, "did"));
    assert_eq!(
        String::from_utf8(verified.payload_bytes).unwrap(),
        s(get(&g, "token"), "signed_body")
    );

    for (env, signer) in [
        (s(get(&g, "challenge"), "wire"), node),
        (s(get(&g, "response"), "wire"), operator),
    ] {
        let parsed = canon::parse(env).unwrap();
        assert_eq!(canon::to_string(&parsed), env, "re-encodes byte for byte");
        let verified =
            envelope::verify(parsed.as_obj().unwrap()).expect("dialogue envelope verifies");
        assert_eq!(verified.signer, s(signer, "did"));
    }

    for a in get(&g, "actions").as_arr().unwrap() {
        let hashed = canon::to_string(&canon::parse(s(a, "hash_input")).unwrap());
        assert_eq!(hashed, s(a, "hash_input"));
        assert_eq!(delta::sha256_hex(hashed.as_bytes()), s(a, "action_hash"));
    }
}

#[test]
fn graph_deltas_agree_with_python() {
    let g = load("graph_delta.json");
    let agent = get(&g, "agent");
    assert_eq!(did_from_seed_hex(s(agent, "seed_hex")), s(agent, "did"));
    for k in get(&g, "state_keys").as_arr().unwrap() {
        let q: Vec<String> = get(k, "query_keys")
            .as_arr()
            .unwrap()
            .iter()
            .map(|x| x.as_str().unwrap().into())
            .collect();
        assert_eq!(state_key(s(k, "origin"), s(k, "route"), &q), s(k, "key"));
    }

    let valid = get(&g, "valid").as_arr().unwrap();
    // Child first: it waits for the root, then both are in.
    let mut store = DagStore::new(Config::new(vec![s(agent, "did").to_string()])).unwrap();
    let (root, child) = (&valid[0], &valid[1]);
    assert_eq!(
        store.insert_wire(s(child, "wire")).unwrap(),
        Outcome::Pending {
            cid: s(child, "cid").into(),
            missing: vec![s(root, "cid").into()]
        }
    );
    assert_eq!(
        store.insert_wire(s(root, "wire")).unwrap(),
        Outcome::Inserted {
            cid: s(root, "cid").into(),
            promoted: vec![s(child, "cid").into()],
            dropped: vec![]
        }
    );
    assert_eq!(store.heads(), vec![s(child, "cid").to_string()]);
    for v in valid {
        assert_eq!(
            delta::cid_of(&canon::parse(s(v, "payload")).unwrap()),
            s(v, "cid")
        );
    }

    for bad in get(&g, "invalid").as_arr().unwrap() {
        let err = store.insert_wire(s(bad, "wire")).expect_err(s(bad, "name"));
        assert!(
            err.0.contains(s(bad, "reason")),
            "{}: got {:?}, want {:?}",
            s(bad, "name"),
            err.0,
            s(bad, "reason")
        );
    }
    assert_eq!(store.len(), 2);
}
