/** English: everything the page says. */

import type { Dict } from './dict.ts';

export const en: Dict = {
  lang: 'en',
  presence: {
    unpaired: 'Symbiont: Not paired',
    pairing: 'Symbiont: Pairing',
    connecting: 'Symbiont: Connecting',
    connected: 'Symbiont: Connected',
    reconnecting: 'Symbiont: Reconnecting',
    busy: 'Symbiont: In use elsewhere',
    refused: 'Symbiont: Not accepted',
    unreachable: 'Symbiont: Out of reach',
    demo: 'Symbiont: Demo',
  },
  presenceHint: {
    unpaired: 'This browser is not paired with your computer yet.',
    pairing: 'Pairing with your computer; done once both sides confirm.',
    connecting: 'Looking for your computer.',
    connected: 'It keeps running in the background; closing this page does not stop it.',
    reconnecting: 'The connection dropped for a moment; reconnecting. Anything unfinished will wait for you.',
    busy: 'Another page is connected to your computer.',
    refused: 'Your computer did not accept this browser.',
    unreachable: 'Your computer is out of reach for now; I will be back as soon as it is.',
    demo: 'This is a demo. It is not connected to any computer and does nothing for real.',
  },
  why: {
    notEnrolled: 'Your computer no longer knows this browser; it needs pairing again.',
    anotherTab: 'You opened me in another tab, so this one steps aside.',
    roomFull: 'Another page is connected to your computer.',
    busy: 'Another page is connected to your computer; I will join once it leaves.',
    badLink: 'This pairing link cannot be used; it may have expired. Run pairing on your computer again.',
    keysUnreadable: 'This browser cannot read its own keys right now. They were left untouched; try again later.',
    w1Failed: 'The other end could not prove it is your computer, so I stopped.',
    pairingRejected: 'Pairing did not finish: your computer did not confirm.',
    pairingUnavailable: 'This pairing has expired. Run pairing on your computer again.',
  },
  ambient: {
    idle: 'All quiet. Say a word below whenever you need me.',
    running: 'Working on what you asked, in the background.',
    waiting: 'A step is waiting for your nod.',
    unpaired: 'This browser is not paired with your computer yet. Run secdogie-node pair on your computer and open the link it gives you.',
    connecting: 'Looking for your computer…',
    demo: 'This is a demo: nothing is connected and nothing really happens.',
    framed: 'For your safety this page cannot be used inside another page. Open it directly.',
  },
  composer: {
    placeholder: 'What should I do?',
    replyPlaceholder: 'Answer the question above…',
    send: 'Send',
    stop: 'Stop',
    offline: 'Once we are connected…',
  },
  reply: {
    accepted: 'On it.',
    refused: 'I cannot take that on right now.',
    stopped: 'Stopped.',
    done: 'Done.',
    notDone: 'That did not work out.',
    stillRunning: 'What you asked earlier is still in progress.',
    undelivered: 'That did not reach your computer; say it again once we are connected.',
    expired: 'That question went unanswered, so the step is on hold.',
  },
  ask: {
    finding: {
      'stale-target': 'The screen just changed, so I want to check before I act.',
      'target-mismatch': "Where I'm about to click doesn't match what I see. Can you confirm?",
      'no-op': "This step doesn't seem to change anything. Still do it?",
      repeated: "I've tried this step a few times already. Try another way?",
      polling: 'Checking over and over is wasteful. Shall I tell you when something changes instead?',
      'destructive-chain': 'Several steps in a row would delete things, so I want to pause and ask.',
      'missing-verification': "The last step isn't confirmed yet. Shall I look before going on?",
      'excessive-cost': 'This is taking a lot of effort. Keep going?',
      'out-of-capability': "This step is outside what I'm allowed to do.",
      'unattended-posting': 'This would go out in your name. Want to look it over first?',
      'unauthorized-action': 'This step needs your authorization.',
      'intent-unproven': "I'm not sure yet whether this step can be undone.",
      'intent-contradiction': 'This step seems to go against what you said. Can you confirm?',
      'precondition-failed': "What this step needs doesn't seem to be in place. Shall I look first?",
      'known-failure': 'This step failed before. Try a different way?',
      empty: "I'm not sure what you'd like yet. Could you say a bit more?",
      contradiction: 'You said just look, but it also sounds like a change. Which is it?',
      overlong: "That's a lot at once. Which part first?",
      'target-unproven': "I haven't found the place you mean yet. Where is it?",
      'target-ambiguous': 'I found two similar places. Is it this one?',
      'graph-destructive': 'What I have mapped is never deleted. Could you put it another way, like where not to look from now on?',
    },
    confirmStep: (action) => `Next I would ${action}. Okay?`,
    confirmPlan: "Here's how I'd go about it. Okay?",
    continueAsk: 'Shall I keep going?',
    yes: 'Okay',
    no: 'Not now',
    answered: (answer) => `You said: ${answer}`,
    waiting: 'This will wait until you are back.',
    expired: 'This question expired; the step is on hold.',
  },
  consent: {
    lead: (action) => `This step will ${action}`,
    graveTail: ', and it cannot be undone.',
    question: 'Are you sure you want to proceed?',
    cancel: 'Cancel',
    approve: 'Approve',
    cannotApprove: 'This browser cannot approve; this step can only be cancelled. To allow it, pair again on your computer and choose to allow it.',
    sending: 'Signing…',
    sent: 'Sent; waiting for your computer.',
    cancelled: 'Cancelled; this step will not happen.',
    waiting: 'Disconnected; confirm when you are back.',
    uncertain: 'Not sure the approval arrived; we will know once reconnected.',
    expired: 'This waited too long and will not happen.',
    refused: "This step's details don't add up, so I did not let you sign it.",
    done: 'Done.',
    notDone: 'In the end this did not happen.',
    tooLong: 'This step is too long to show you in full, so I will not let you approve it.',
    quoteLabel: { name: 'Target', text: 'Content', where: 'Where' },
  },
  action: {
    click: (name) => `click “${name}”`,
    clickBlind: 'click on the screen',
    type: (name) => `type the text below into “${name}”`,
    typeBlind: 'type the text below on the screen',
    key: (keys) => `press ${keys}`,
    submit: (name) => `submit “${name}”`,
    open: (name) => `open “${name}”`,
    direct: (name) => name.charAt(0).toLowerCase() + name.slice(1),
    other: (kind, name) => (name ? `do “${kind}” on “${name}”` : `do “${kind}”`),
    on: (host) => ` (on ${host})`,
    theTarget: 'the target below',
  },
  pairing: {
    checking: 'Making sure the other end is your computer…',
    confirm: 'Connect this browser to your computer?',
    compare: 'Check that your computer’s terminal shows the same digits, then tap Connect.',
    connect: 'Connect',
    cancel: 'Cancel',
    sent: 'Confirmed. Waiting for your computer to agree…',
    refused: 'Pairing did not finish.',
  },
};
