/** 中文：页面上说的每一句话。 */

import type { Dict } from './dict.ts';

export const zh: Dict = {
  lang: 'zh-CN',
  presence: {
    unpaired: '共生体: 未配对',
    pairing: '共生体: 正在配对',
    connecting: '共生体: 正在连接',
    connected: '共生体: 已连接',
    reconnecting: '共生体: 重新连接中',
    busy: '共生体: 在别处使用中',
    refused: '共生体: 连接未被接受',
    unreachable: '共生体: 暂时联系不上',
    demo: '共生体: 演示',
  },
  presenceHint: {
    unpaired: '这个浏览器还没和你的电脑配对。',
    pairing: '正在和你的电脑配对，两边都确认后就好了。',
    connecting: '正在找你的电脑。',
    connected: '后台一直在运行，关掉这个页面也不会打断它。',
    reconnecting: '连接断了一下，正在接回去。没说完的事会等你。',
    busy: '另一个页面正连着你的电脑。',
    refused: '你的电脑没有接受这个浏览器。',
    unreachable: '暂时联系不上你的电脑，它一上线我就回来。',
    demo: '这是演示，不连接任何电脑，也不会真的做任何事。',
  },
  why: {
    notEnrolled: '你的电脑不再认这个浏览器了，需要重新配对。',
    anotherTab: '你在另一个标签页里打开了我，这边先让一让。',
    roomFull: '另一个页面正连着你的电脑。',
    busy: '另一个页面正连着你的电脑，等它离开我再接上。',
    badLink: '这个配对链接用不了，可能过期了。请在电脑上重新运行配对。',
    keysUnreadable: '这个浏览器暂时读不出自己的钥匙。没有动它们，稍后再试试。',
    w1Failed: '连上的那一端证明不了自己是你的电脑，我没有继续。',
    pairingRejected: '配对没有完成：电脑那边没有确认。',
    pairingUnavailable: '这次配对已经失效了，请在电脑上重新运行配对。',
  },
  ambient: {
    idle: '一切安静。有事就在下面说一声。',
    running: '后台正在做你交代的事。',
    waiting: '有一步在等你点头。',
    unpaired: '这个浏览器还没和你的电脑配对。在电脑上运行 secdogie-node pair，再打开它给出的链接。',
    connecting: '正在找你的电脑……',
    demo: '这是演示：没有连接任何电脑，什么都不会真的发生。',
    framed: '为了安全，这个页面不能嵌在别的网页里使用。请直接打开它。',
  },
  composer: {
    placeholder: '想让我做什么？',
    replyPlaceholder: '回答上面的问题……',
    send: '发送',
    stop: '停下',
    offline: '等连上了再说……',
  },
  reply: {
    accepted: '好，这就去做。',
    refused: '这件事现在接不了。',
    stopped: '好，停下了。',
    done: '做完了。',
    notDone: '这件事没做成。',
    stillRunning: '你之前交代的事还在做。',
    undelivered: '刚才那句没送到你的电脑，连上以后再说一次吧。',
    expired: '这个问题没等到回答，那一步先放着了。',
  },
  ask: {
    finding: {
      'stale-target': '屏幕上的东西刚变过，我想先确认一下再动手。',
      'target-mismatch': '我要点的地方和看到的对不上，帮我确认一下？',
      'no-op': '这一步好像什么都不会改变，还要做吗？',
      repeated: '这一步我已经试过几次了，要换个方式吗？',
      polling: '一直反复去看会很费劲，换成有变化时再提醒你，好吗？',
      'destructive-chain': '接连几步都会删掉东西，我想先停一下问问你。',
      'missing-verification': '上一步还没确认成功，要我先看一眼再继续吗？',
      'excessive-cost': '这件事要花的工夫有点多，确定要继续吗？',
      'out-of-capability': '这一步超出了我被允许做的范围。',
      'unattended-posting': '这会以你的名义发出去，想先过目一下吗？',
      'unauthorized-action': '这一步需要你的授权才能做。',
      'intent-unproven': '这一步做完能不能撤回，我还没弄清楚。',
      'intent-contradiction': '这一步和你说的好像有点矛盾，帮我确认一下？',
      'precondition-failed': '做这一步的前提好像不满足，要我先看看吗？',
      'known-failure': '这一步以前失败过，要换个做法吗？',
      empty: '我还不太清楚你想做什么，能说具体一点吗？',
      contradiction: '你说只看看，又像是要改东西，是哪一个呢？',
      overlong: '一次要做的事有点多，先从哪一件开始？',
      'target-unproven': '我还没找到你说的那个地方，能再说说在哪吗？',
      'target-ambiguous': '刚才找到了两个相似的地方，帮你确认一下是这个吗？',
      'graph-destructive': '我记下的路径不会删除，换个说法好吗？比如以后不再看哪些地方。',
    },
    confirmStep: (action) => `接下来要${action}，可以吗？`,
    confirmPlan: '我打算这样做，可以吗？',
    continueAsk: '要我继续吗？',
    yes: '可以',
    no: '先不要',
    answered: (answer) => `你说：${answer}`,
    waiting: '等你回来再回答。',
    expired: '这个问题过期了，那一步先放着。',
  },
  consent: {
    lead: (action) => `这一步会${action}`,
    graveTail: '，做完就没法恢复了。',
    question: '确认要继续吗？',
    cancel: '取消',
    approve: '批准',
    cannotApprove: '这个浏览器没有批准权限，这一步只能取消；要开启，请在电脑上重新配对并选择允许。',
    sending: '正在签名……',
    sent: '已发出，等你的电脑确认。',
    cancelled: '已取消，这一步不会发生。',
    waiting: '连接断了，等你回来再确认。',
    uncertain: '不确定刚才的确认有没有送到，连上以后会知道结果。',
    expired: '等太久了，这一步不会发生。',
    refused: '这一步的内容对不上，我没有让你签。',
    done: '已完成。',
    notDone: '这件事最后没有做成。',
    tooLong: '这一步的内容太长，没法完整给你看，所以我不让你批准它。',
    quoteLabel: { name: '对象', text: '内容', where: '位置' },
  },
  action: {
    click: (name) => `点一下「${name}」`,
    clickBlind: '在屏幕上点一下',
    type: (name) => `在「${name}」里输入下面这段文字`,
    typeBlind: '在屏幕上输入下面这段文字',
    key: (keys) => `按下 ${keys}`,
    submit: (name) => `提交「${name}」`,
    open: (name) => `打开「${name}」`,
    direct: (name) => `直接${name}`,
    other: (kind, name) => (name ? `对「${name}」做一次「${kind}」` : `做一次「${kind}」`),
    on: (host) => `（在 ${host}）`,
    theTarget: '下面这个对象',
  },
  pairing: {
    checking: '正在确认对面是你的电脑……',
    confirm: '要把这个浏览器连到你的电脑吗？',
    compare: '看看电脑终端上是不是同样的数字，一样再点「连接」。',
    connect: '连接',
    cancel: '取消',
    sent: '已确认。等电脑那边也点头……',
    refused: '配对没有完成。',
  },
};
