#!/usr/bin/env bash
# setup-cloudflare-tunnel.sh — operator machine, outbound-only named tunnel.
set -euo pipefail

NAME="${1:-secdogie-atlas}"
HOST="${2:-}"
CONFIG_OUT="${HOME}/.cloudflared/config.yml"

if [[ -z "$HOST" ]]; then
  echo "usage: $0 <tunnel-name> <hostname>" >&2
  exit 2
fi
if [[ "$HOST" == *"://"* ]]; then
  echo "hostname only — no scheme" >&2
  exit 2
fi
if ! command -v cloudflared >/dev/null 2>&1; then
  echo "cloudflared not found. See Cloudflare Tunnel downloads." >&2
  exit 1
fi

cloudflared tunnel login
cloudflared tunnel create "$NAME"
cloudflared tunnel route dns "$NAME" "$HOST"

mkdir -p "$(dirname "$CONFIG_OUT")"
cat > "$CONFIG_OUT" <<EOF
# generated by SecDogie Atlas — do not commit credentials
tunnel: ${NAME}
credentials-file: ${HOME}/.cloudflared/${NAME}.json
protocol: quic
no-autoupdate: true
ingress:
  - hostname: ${HOST}
    service: http://127.0.0.1:17890
    originRequest:
      noTLSVerify: false
      connectTimeout: 10s
      keepAliveTimeout: 90s
  - service: http_status:404
EOF

echo "Wrote $CONFIG_OUT"
echo "Start: cloudflared tunnel --config $CONFIG_OUT run $NAME"
echo "Put Cloudflare Access in front of $HOST before exposing the agent."
