# setup-cloudflare-tunnel.ps1
# Operator machine. Requires cloudflared in PATH and a Cloudflare account.
# Does not open inbound ports. Named tunnel, outbound QUIC, TLS at the edge.

[CmdletBinding()]
param(
  [string]$Name = "secdogie-atlas",
  [Parameter(Mandatory = $true)][string]$Hostname,
  [string]$ConfigOut = $(Join-Path $env:USERPROFILE ".cloudflared\config.yml")
)

$ErrorActionPreference = "Stop"

if (-not (Get-Command cloudflared -ErrorAction SilentlyContinue)) {
  throw @"
cloudflared not found.
Install: https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/
"@
}

if ($Hostname -match "://") {
  throw "Hostname only — no scheme. Example: atlas.example.com"
}

cloudflared tunnel login
cloudflared tunnel create $Name
cloudflared tunnel route dns $Name $Hostname

$ConfigDir = Split-Path -Parent $ConfigOut
New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null

@"
# generated by SecDogie Atlas — do not commit credentials
tunnel: $Name
credentials-file: $ConfigDir\$Name.json
protocol: quic
no-autoupdate: true
ingress:
  - hostname: $Hostname
    service: http://127.0.0.1:17890
    originRequest:
      noTLSVerify: false
      connectTimeout: 10s
      keepAliveTimeout: 90s
  - service: http_status:404
"@ | Set-Content -Path $ConfigOut -Encoding utf8

Write-Host "Wrote $ConfigOut"
Write-Host "Start: cloudflared tunnel --config $ConfigOut run $Name"
Write-Host "Put Cloudflare Access in front of $Hostname before exposing the agent."
