// The browser link against fixtures/vectors/link.json (generated by the Python
// reference): frames, mux, session framing, every dialogue/v1 packet the page
// sends or receives, W1 statements, the pairing set and its check code --
// produced here byte for byte, and opened here when Python made them.
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

import { type CanonObject, canonicalText, fromHex, parseLossless, toHex } from '../src/core/canon.ts';
import { WebCryptoSigner } from '../src/core/ed25519.ts';
import { TrustSet } from '../src/core/envelope.ts';
import { type Header, type Packet, PacketKind, ReplayGuard, openEnvelope, packetWire, seal } from '../src/gate2/wire.ts';
import { DirectFrames, ReplayWindow } from '../src/net/frame.ts';
import * as la from '../src/net/linkauth.ts';
import { muxDecode, muxEncode } from '../src/net/mux.ts';
import { DialogueSession, ackFrame, fragments } from '../src/net/session.ts';

const v = JSON.parse(readFileSync(new URL('../../fixtures/vectors/link.json', import.meta.url), 'utf8'));
const AT = Number(v.issued_at);

const ids = async () => ({
  app: await WebCryptoSigner.fromSeed(fromHex(v.app.seed_hex)),
  operator: await WebCryptoSigner.fromSeed(fromHex(v.operator.seed_hex)),
  node: await WebCryptoSigner.fromSeed(fromHex(v.node.seed_hex)),
});

test('identities', async () => {
  const { app, operator, node } = await ids();
  assert.deepEqual([app.did, operator.did, node.did], [v.app.did, v.operator.did, v.node.did]);
});

test('mux encodes and decodes like Python, and refuses the same garbage', () => {
  for (const c of v.mux.cases) {
    assert.equal(toHex(muxEncode(c.channel, fromHex(c.payload_hex))), c.wire_hex);
    const d = muxDecode(fromHex(c.wire_hex));
    assert.equal(d?.channel, c.channel);
    assert.equal(toHex(d!.payload), c.payload_hex);
  }
  for (const bad of v.mux.reject_hex) assert.equal(muxDecode(fromHex(bad)), null, bad);
});

test('session fragments and acks are the Python bytes', () => {
  const s = v.session;
  const frames = fragments(BigInt(s.msg_id), fromHex(s.data_hex), { reliable: true, size: s.fragment_size });
  assert.deepEqual(frames.map(toHex), s.frames_hex);
  assert.equal(toHex(fragments(7n, new TextEncoder().encode('hb'), { reliable: false })[0]!), s.unreliable_frame_hex);
  assert.equal(toHex(ackFrame(BigInt(s.msg_id))), s.ack_hex);
});

test('the replay window takes the same steps', () => {
  const w = new ReplayWindow(v.replay_window.size);
  assert.deepEqual(
    v.replay_window.steps.map((s: { ctr: number }) => w.accept(BigInt(s.ctr))),
    v.replay_window.steps.map((s: { accept: boolean }) => s.accept),
  );
});

test('direct frames: the signed body and signature match, and Python frames open', async () => {
  const { app, node } = await ids();
  const byName = Object.fromEntries(v.frames.map((f: { name: string }) => [f.name, f]));
  const ab = byName['app_to_node'];
  const appFrames = new DirectFrames({ self: app, peerDid: node.did, trust: new TrustSet([node.did]), clockNs: () => 0n });
  const built = await appFrames.frame(fromHex(ab.message_hex), BigInt(ab.ctr));
  const { signer: _s, sig, ...body } = built as Record<string, unknown>;
  assert.equal(canonicalText(body as CanonObject), ab.signed_body);
  assert.equal(sig, ab.sig);
  // a frame the Python node sent opens here once, and only once
  const na = byName['node_to_app'];
  const raw = new TextEncoder().encode(na.wire);
  assert.equal(toHex((await appFrames.open(raw))!), na.message_hex);
  assert.equal(await appFrames.open(raw), null, 'a replayed frame is dropped');
  // ...and a frame from anyone else, or for anyone else, never opens
  const nodeFrames = new DirectFrames({ self: node, peerDid: app.did, trust: new TrustSet([app.did]) });
  assert.equal(await nodeFrames.open(raw), null, 'addressed to the app, not the node');
  const tampered = new TextEncoder().encode(na.wire.replace(na.ctr, (BigInt(na.ctr) + 1n).toString()));
  const fresh = new DirectFrames({ self: app, peerDid: node.did, trust: new TrustSet([node.did]) });
  assert.equal(await fresh.open(tampered), null, 'a changed counter breaks the signature');
});

test('every dialogue/v1 packet: Python envelopes open here, and sealing here gives the same bytes', async () => {
  const { app, node } = await ids();
  for (const e of v.envelopes) {
    const [sender, recipient] = e.from === 'app' ? [app, node] : [node, app];
    const obj = parseLossless(e.wire);
    assert.equal(canonicalText(obj), e.canonical, e.name);
    const header = (obj as CanonObject)['header'] as CanonObject;
    const ts = header['timestamp_ns'] as bigint;
    const opened = await openEnvelope(obj, {
      trust: new TrustSet([sender.did]),
      selfDid: recipient.did,
      replay: new ReplayGuard({ clockNs: () => ts }),
    });
    assert.ok(opened.ok, `${e.name}: ${opened.ok ? '' : opened.reason}`);
    if (!opened.ok) continue;
    if (opened.packet.kind === PacketKind.StateSnapshot) {
      assert.equal(opened.packet.packet, null, 'a snapshot is admitted and dropped');
      continue;
    }
    const resealed = await seal(sender, opened.header as Header, opened.packet as Packet);
    assert.equal(canonicalText(resealed), e.canonical, `${e.name} resealed`);
    assert.equal(canonicalText(packetWire(opened.packet)), canonicalText((obj as CanonObject)['payload']!));
  }
});

test('SDP fingerprints and the data-only check', () => {
  for (const [name, text] of Object.entries(v.sdp.texts as Record<string, string>)) {
    assert.deepEqual(la.fingerprintsFromSdp(text), v.sdp.fingerprints[name], name);
  }
  assert.ok(la.sdpIsDataOnly(v.sdp.texts.browser_local));
  assert.ok(la.sdpIsDataOnly(v.sdp.texts.aiortc_local));
  assert.ok(!la.sdpIsDataOnly(v.sdp.texts.with_video));
});

test('W1: the page states what Python states, and checks the node the way Python does', async () => {
  const { app, node } = await ids();
  for (const shape of v.w1.shapes) {
    const mine = await la.createLinkBinding(app, { room: v.w1.room, local: shape.page_local, remote: shape.page_remote, issuedAt: AT });
    assert.equal(canonicalText(mine), shape.page_binding, shape.name);
    const theirs = await la.createLinkBinding(node, { room: v.w1.room, local: shape.node_local, remote: shape.node_remote, issuedAt: AT });
    assert.equal(canonicalText(theirs), shape.node_binding, shape.name);
    const r = await la.verifyLinkBinding(parseLossless(shape.node_binding), {
      trust: new TrustSet([node.did]), room: v.w1.room, observedLocal: shape.page_local, observedRemote: shape.page_remote, now: AT,
    });
    assert.ok(r.ok, `${shape.name}: ${r.reason}`);
  }
  const nodeBinding = parseLossless(v.w1.shapes[0].node_binding);
  for (const bad of v.w1.rejects) {
    const r = await la.verifyLinkBinding(nodeBinding, {
      trust: new TrustSet([node.did]), room: v.w1.room, observedLocal: bad.page_local, observedRemote: bad.page_remote, now: AT,
    });
    assert.equal(r.reason, bad.reason, bad.name);
  }
  const stranger = await la.verifyLinkBinding(nodeBinding, {
    trust: new TrustSet([app.did]), room: v.w1.room, observedLocal: v.w1.shapes[0].page_local, observedRemote: v.w1.shapes[0].page_remote, now: AT,
  });
  assert.equal(stranger.reason, 'signer not trusted');
  const late = await la.verifyLinkBinding(nodeBinding, {
    trust: new TrustSet([node.did]), room: v.w1.room, observedLocal: v.w1.shapes[0].page_local, observedRemote: v.w1.shapes[0].page_remote, now: AT + 121,
  });
  assert.equal(late.reason, 'stale or future statement');
});

test('pairing: the link, the hello, the code, the tap, the receipt -- all Python bytes', async () => {
  const { app, operator, node } = await ids();
  const p = v.pairing;
  const invite = await la.parsePairingFragment(p.fragment, AT);
  assert.equal(invite.nodeDid, node.did);
  assert.equal(la.b64url(invite.secret), p.secret_b64url);
  assert.equal(invite.pairingId, p.pairing_id);
  assert.equal(invite.room, p.pairing_room);
  const hello = await la.createPairHello(app, { invite, local: p.page_local, remote: p.page_remote, operatorDid: operator.did, issuedAt: AT });
  assert.equal(canonicalText(hello), p.hello);
  assert.equal(await la.checkCode(hello), p.check_code);
  assert.match(p.check_code, /^\d{4} \d{4} \d{4}$/);
  assert.equal(await la.helloHash(hello), p.hello_hash);
  const proof = await la.createOperatorProof(operator, { appDid: app.did, nodeDid: node.did, pairingId: invite.pairingId, issuedAt: AT + 5 });
  assert.equal(canonicalText(proof), p.operator_proof);
  const confirm = await la.createPairConfirm(app, { invite, hello, operatorProof: proof, issuedAt: AT + 5 });
  assert.equal(canonicalText(confirm), p.confirm);
  const paired = await la.verifyPaired(parseLossless(p.paired), {
    nodeDid: node.did, appDid: app.did, pairingId: p.pairing_id, observedLocal: p.page_local, observedRemote: p.page_remote, now: AT + 6,
  });
  assert.ok(paired.ok, paired.reason ?? '');
  assert.equal(paired.room, v.room.room);
  assert.equal(paired.operatorDid, operator.did);
  for (const [reason, text] of Object.entries(p.refused as Record<string, string>)) {
    const r = await la.verifyRefusal(parseLossless(text), { nodeDid: node.did, observedLocal: p.page_local, observedRemote: p.page_remote, now: AT + 6 });
    assert.equal(r.refusal, reason);
    const forged = await la.verifyRefusal(parseLossless(text), { nodeDid: app.did, observedLocal: p.page_local, observedRemote: p.page_remote, now: AT + 6 });
    assert.equal(forged.ok, false, 'a refusal from another node is not a refusal');
  }
});

test('a crafted pairing link cannot name a gateway or ICE servers, or outlive its expiry', async () => {
  const p = v.pairing;
  const body = JSON.parse(new TextDecoder().decode(la.b64urlDecode(p.fragment.slice(5))));
  const evil = 'pair=' + la.b64url(new TextEncoder().encode(JSON.stringify({ ...body, signal: 'wss://evil.example/ws' })));
  await assert.rejects(la.parsePairingFragment(evil, AT), /unknown/);
  const ice = 'pair=' + la.b64url(new TextEncoder().encode(JSON.stringify({ ...body, ice: ['stun:evil.example'] })));
  await assert.rejects(la.parsePairingFragment(ice, AT), /unknown/);
  await assert.rejects(la.parsePairingFragment(p.fragment, p.expires_at), /expired/);
  for (const bad of ['', '#demo', 'pair=', 'pair=!!', `pair=${la.b64url(new TextEncoder().encode('[]'))}`]) {
    await assert.rejects(la.parsePairingFragment(bad, AT));
  }
});

test('finding kinds the page has to word are listed', () => {
  assert.equal(v.finding_kinds.length, 15);
});

test('a session over a lossy pipe: fragments, acks, retransmits, one delivery each', async () => {
  const { app, node } = await ids();
  let t = 100;
  const clock = () => t;
  const ns = () => BigInt(Date.now()) * 1_000_000n;
  const wire: Array<[string, Uint8Array]> = [];
  let drop = 0;
  const mk = (self: WebCryptoSigner, peer: WebCryptoSigner, name: string) =>
    new DialogueSession({
      self, peerDid: peer.did, trust: new TrustSet([peer.did]), clock, clockNs: ns, fragmentSize: 64,
      send: (f) => {
        if (drop > 0) {
          drop -= 1;
          return;
        }
        wire.push([name, f]);
      },
    });
  const a = mk(app, node, 'to-node');
  const n = mk(node, app, 'to-app');
  const got: Packet[] = [];
  n.onEnvelope = (d) => got.push(d.packet);
  const pump = async () => {
    while (wire.length) {
      const [to, f] = wire.shift()!;
      await (to === 'to-node' ? n : a).receive(f);
    }
  };
  drop = 2; // the first two fragments are lost
  await a.send({ kind: PacketKind.Control, packet: { request_id: 'r1', op: 'add_goal', goal_id: 'g1', title: '注销旧账号 '.repeat(20), memory_id: '', confirmation: {} } });
  await pump();
  assert.equal(got.length, 0);
  assert.equal(a.pending, 1);
  t += 0.3;
  a.tick(t);
  await pump();
  assert.equal(got.length, 1);
  assert.equal(a.pending, 0, 'acknowledged');
  // a duplicate (a late retransmission) is acknowledged but not delivered again
  t += 1;
  a.tick(t);
  await pump();
  assert.equal(got.length, 1);
});

test('a session gives up and says so; liveness goes down and comes back', async () => {
  const { app, node } = await ids();
  let t = 0;
  const failed: bigint[] = [];
  const events: string[] = [];
  const a = new DialogueSession({
    self: app, peerDid: node.did, trust: new TrustSet([node.did]), clock: () => t, send: () => undefined, heartbeatInterval: 2,
  });
  a.onUndeliverable = (id) => failed.push(id);
  a.onPeerDown = () => events.push('down');
  a.onPeerUp = () => events.push('up');
  const id = await a.send({ kind: PacketKind.Session, packet: { event: 'hello', note: '' } });
  for (let i = 0; i < 40; i++) {
    t += 0.5;
    a.tick(t);
  }
  assert.deepEqual(failed, [id]);
  assert.deepEqual(events, ['down']);
  await a.receive(new Uint8Array([0x41, 0, 0, 0, 0, 0, 0, 0, 0]));
  assert.deepEqual(events, ['down', 'up']);
});
