/** Every word the stream shows, in one place. Chinese by default. */

export const zh = {
  gate1Tag: 'Gate 1 · 先想清楚',
  gate2Tag: 'Gate 2 · 需要你的签名',
  findings: {
    empty: '没有具体目标',
    contradiction: '前后矛盾',
    'unattended-posting': '无人值守的发布',
    polling: '低效轮询',
    overlong: '一次做太多',
    'target-unproven': '拓扑里没有这个目标',
    'target-ambiguous': '目标不明确',
    'graph-destructive': '想删除已映射的状态',
    'intent-unproven': '没说清能否撤回',
    'intent-contradiction': '意图自相矛盾',
  } as Record<string, string>,
  answerPlaceholder: '用你自己的话回答…',
  answer: '回答',
  answered: '你回答了：',
  probeExpired: '这个问题没等到回答，我把这件事先放下了。',
  risk: { low: '低风险', high: '高风险', irreversible: '不可撤回' } as Record<string, string>,
  field: {
    kind: '动作',
    target_name: '目标',
    target_role: '类型',
    text: '内容',
    target_id: '状态键',
    high_risk: '高风险',
  } as Record<string, string>,
  hashOk: '本地重算一致',
  hashBad: '与节点声称的不一致',
  validUntil: (hhmm: string) => `有效至 ${hhmm}`,
  approve: '批准并签名',
  deny: '拒绝',
  bubbleState: {
    awaiting: '',
    signing: '正在用你的密钥签名…',
    approved: '已签名放行。',
    denied: '你拒绝了，这个动作不会发生。',
    refused: '我没有让你签：',
    expired: '没等到签名，节点会拒绝这个动作。',
  } as Record<string, string>,
  veiled: '有一项需要你看。现在的画面不适合展开，稍后再显示。',
  held: (n: number) => `还有 ${n} 件事等你空下来再说。`,
  yes: '是',
  no: '否',
  ambient: {
    swarm: (peers: number, heads: number, deltas: number) =>
      `群体：${peers} 个节点相连，图上 ${deltas} 条增量、${heads} 个前沿`,
    synced: (sec: number) => (sec < 60 ? `，${sec} 秒前同步过` : `，${Math.round(sec / 60)} 分钟前同步过`),
    neverSynced: '，还没有和别的节点同步',
    topology: (origins: number, states: number, refs: number) =>
      `拓扑：${origins} 个站点，${states} 个状态，${refs} 条引用`,
    recent: (n: number) => `，最近新增 ${n} 个`,
    mode: {
      flow: '你正专注，我先安静地记着。',
      engaged: '你在忙，等你停一停再说。',
      gap: '',
      away: '你不在，事情先替你攒着。',
      suppressed: '当前画面敏感，所有内容先收起来。',
    } as Record<string, string>,
  },
  narrate: {
    mapped: (host: string, n: number, pages: number) =>
      `在 ${host} 梳理出 ${n} 个候选状态${pages > 1 ? `（看了 ${pages} 个页面）` : ''}`,
    synced: (peers: number, n: number) => `和 ${peers} 个节点交换了 ${n} 条增量`,
    fetchRefused: (host: string, n: number, reason: string) =>
      `${host} 没有放行抓取${n > 1 ? ` ${n} 次` : ''}（${reason}），我没有绕过`,
    aligned: (s: string) => `想清楚了：${s}`,
    declined: (s: string) => `没有动手：${s}`,
    expired: (s: string) => `没等到你的回答，「${s}」先放下了`,
    released: (s: string) => `已放行：${s}`,
    refused: (s: string, why: string) => `没有放行：${s}（${why}）`,
  },
} as const;
